<table style="width:970px; border:0px;">
    <tr>
    <td>
      <div style="width:161px; text-align:center; border-width: 0px; margin-top: 5px;"><img src="http://www.acureofbloodflowers.com/bibliografia/fotos/bibliografia.gif" style="width:116px; height:35px;" /></div></td>
      <td style="width:161px; vertical-align: middle;"><div align="center"><a href="http://www.acureofbloodflowers.com/bibliografia/esp/bibliografiaEspanola.php" target="_self"><img src="http://www.acureofbloodflowers.com/bibliografia/fotos/SPAIN.GIF" alt="Española" width="22" height="15" border="0" /></a><a href="http://www.acureofbloodflowers.com/bibliografia/esp/bibliografiaEspanola.php" target="_self"> Espa&ntilde;ola</a></div></td>
      <td style="width:161px; vertical-align:middle;"><div align="center"><a href="http://www.acureofbloodflowers.com/bibliografia/brit/bibliografiaBritanica.php" target="_self"><img src="http://www.acureofbloodflowers.com/bibliografia/fotos/uk.gif" alt="Británica" width="22" height="15" border="0" /></a><a href="http://www.acureofbloodflowers.com/bibliografia/brit/bibliografiaBritanica.php" target="_self"> Brit&aacute;nica</a></div></td>
      <td style="width:161px; vertical-align:middle;"><div align="center"><a href="http://www.acureofbloodflowers.com/bibliografia/franc/bibliografiaFrancesa.php" target="_self"><img src="http://www.acureofbloodflowers.com/bibliografia/fotos/FRANCE.GIF" alt="Francesa" width="22" height="15" border="0" /></a><a href="http://www.acureofbloodflowers.com/bibliografia/franc/bibliografiaFrancesa.php" target="_self"> Francesa</a></div></td>
      <td style="width:161px; vertical-align:middle;"><div align="center"><a href="http://www.acureofbloodflowers.com/bibliografia/tabs/tabs.php" target="_self"><img src="http://www.acureofbloodflowers.com/bibliografia/fotos/Tabs.GIF" alt="Parituras" width="22" height="15" border="0" /></a><a href="http://www.acureofbloodflowers.com/bibliografia/tabs/tabs.php" target="_self"> TABS...</a></div></td>
      <td style="width:161px; vertical-align:middle;"><div align="center"> <a href="http://www.acureofbloodflowers.com/bibliografia/bibliografiaLg.php" target="_self"><img src="http://www.acureofbloodflowers.com/bibliografia/fotos/Libgira.gif" alt="Libros de gira" width="22" height="15" border="0" /></a><a href="http://www.acureofbloodflowers.com/bibliografia/bibliografiaLg.php" target="_self">  Libros de Gira</a></div></td>
    </tr>
  </table>